<a href="https://colab.research.google.com/github/sammyHa/python_data_science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy uses contiguous memory. its faster then python lists.

##Benefits of using numpy:
*   SIMD Vector processing
*   Effective Cache Utilization


Insertion, deletion etc.

* eg: list: a = [1, 2, 3]
            b = [1, 2, 3]
            a * b = ERROR
* eg: Numpy: a * b = np.array([1, 6, 15])

## Application of Numpy
* Mathematics (replacement of MATHLAB)
* PLOTTING (Mathplotlib)
* Backend (Pandas, Connect 4, Ditital Photography)
* Important for Machine Learning 






In [ ]:
import numpy as np


In [ ]:
## init array
a = np.array([1, 2 ,3],dtype='int8' )
print(a)

[1 2 3]


In [ ]:
## multi-dim array
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get Dimension
b.ndim

2

In [ ]:
# Get shape
b.shape

(2, 3)

In [ ]:
#Get type
a.dtype

dtype('int64')

In [ ]:
# Get Size, change the dtype='int16, int32, and default is int64 in the array above
a.itemsize

1

In [ ]:
# total size of the item number of bytes
a.nbytes


3

## Accessing/Changing specific elements, rows, columns etc

In [ ]:
c = np.array([[1, 2 ,3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13 ,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific elemetnt in array [r, c]

c [1, 5]

13

In [ ]:
# Get specifi row, using the slice (:) to get all the columns
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [ ]:
# Getting the start and end with spteps columns => syntax [startindex:endindex:stepsize]

c [0, 1:6:2]

array([2, 4, 6])

In [ ]:
# alter the array and replace elements
c [1, 5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
# replace the entire column
c [:, 2] = [1, 2]
print(c)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3-d example
